# Generated by Django 4.2 on 2024-01-31 06:59

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20220208_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=post.models.user_directory_path, verbose_name='Picture')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('desig', models.CharField(blank=True, max_length=100, null=True)),
                ('quali', models.CharField(blank=True, max_length=500, null=True)),
                ('facultyy', models.CharField(blank=True, choices=[('Engg', 'Faculty of Engineering'), ('SC', 'Faculty of Science'), ('Comm', 'Faculty of Commerce'), ('Arts', 'Faculty of Arts'), ('Arch', 'Faculty of Architecture'), ('SS', 'Faculty of Social Science'), ('Ayush', 'Faculty of Ayush'), ('TC', 'Technical College')], max_length=50, null=True)),
                ('phone', models.IntegerField(blank=True, max_length=15, null=True)),
                ('gmail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
