# Generated by Django 4.2 on 2024-03-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_professor_user_alter_professor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('jd', models.FileField(blank=True, default='no.jpg', null=True, upload_to='pdf')),
                ('students_placed', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('1', 'Completed'), ('2', 'Ongoing'), ('3', 'Cancelled'), ('4', 'Waiting'), ('5', 'Coming Soon'), ('6', 'Postponed'), ('7', 'Preponed')], max_length=50)),
            ],
        ),
    ]
