# Generated by Django 4.2 on 2024-03-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_rename_caption_placement_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='status',
            field=models.CharField(choices=[('Completed', '1'), ('Ongoing', '2'), ('Cancelled', '3'), ('Waiting', '4'), ('Coming Soon', '5'), ('Postponed', '6'), ('Preponed', '7')], max_length=50),
        ),
    ]
