# Generated by Django 4.2 on 2024-03-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_alter_placement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
