# Generated by Django 4.2 on 2024-03-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_placement_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=10)),
                ('Course', models.CharField(blank=True, max_length=100, null=True)),
                ('Branch', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('Link', models.FileField(blank=True, default='no.jpg', null=True, upload_to='pdf')),
            ],
        ),
    ]
