# Generated by Django 4.2 on 2024-03-27 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='Branch',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='Link',
            new_name='link',
        ),
    ]
