# Generated by Django 4.2 on 2024-03-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_rename_branch_notes_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, default='no.jpg', null=True, upload_to='profile_pciture')),
            ],
        ),
    ]
