# Generated by Django 4.2 on 2024-03-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_alumni'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='image',
            field=models.ImageField(blank=True, default='no.jpg', null=True, upload_to='profile_pciture'),
        ),
    ]
