# Generated by Django 4.2 on 2024-03-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_alumni_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='branch',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
