# Generated by Django 4.2 on 2024-04-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Placed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=10)),
                ('job_role', models.CharField(max_length=10)),
                ('link', models.CharField(max_length=10)),
            ],
        ),
    ]
