# Generated by Django 4.2 on 2024-04-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_student_placed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_placed',
            name='job_role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student_placed',
            name='link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student_placed',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
