# Generated by Django 4.2 on 2024-04-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_placed',
            name='batch',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
