# Generated by Django 4.2 on 2024-03-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_dpost_dcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100)),
                ('faculty_m', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
