# Generated by Django 4.2 on 2024-03-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_notif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='faculty_m',
            field=models.CharField(blank=True, choices=[('Engineering', 'Faculty of Engineering'), ('Science', 'Faculty of Science'), ('Arts', 'Faculty of Arts')], max_length=100, null=True),
        ),
    ]
