# Generated by Django 4.2 on 2024-03-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_alter_notif_faculty_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
