# Generated by Django 4.2 on 2024-03-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_notif_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
