# Generated by Django 4.2 on 2024-03-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_alter_notif_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpost',
            name='image',
            field=models.ImageField(blank=True, default='no.jpg', null=True, upload_to='profile_pciture'),
        ),
    ]
